import {category} from './category';

export let products: ({ gal2: string; image: string[]; gal3: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: string; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string } | { gal2: string; gal3: string; img: string; price: number; name: string; rating: number; link: string; description: string; id: number; category: number; gal1: string })[];
products = [
  {
    id: 1,

    name: 'CeraVe Moisturizing Cream ',
    img: 'https://m.media-amazon.com/images/I/61S7BrCBj7L._AC_UL480_QL65_.jpg',
    gal1: 'https://m.media-amazon.com/images/I/61S7BrCBj7L._AC_UL480_QL65_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/61lO1d7FSsL._SL1000_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61RzTGeRKRL._SL1000_.jpg',
    price: 18.99,
    rating: 4.9,
    link: 'https://www.amazon.com/CeraVe-Moisturizing-Cream-Daily-Moisturizer/dp/B00TTD9BRC/ref=sr_1_2?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-2',
    description: 'With hyaluronic acid, ceramides and MVE technology for 24 hour hydration. Rich, velvety texture that leaves skin feeling smooth, it is absorbed quickly for softened skin without greasy, sticky, feel.',
    category: 1,
  },

  {
    id: 2,

    name: 'TruSkin Vitamin C Serum for Face',
    img: 'https://m.media-amazon.com/images/I/516yN4iPdQL._AC_UL480_QL65_.jpg',
    gal1: 'https://m.media-amazon.com/images/I/516yN4iPdQL._AC_UL480_QL65_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71cDoRe7XkL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/51qwH8YGR9L.jpg',
    price: 29.99,
    rating: 4.0,
    link: 'https://www.amazon.com/TruSkin-Naturals-Vitamin-Topical-Hyaluronic/dp/B01M4MCUAF/ref=sr_1_9?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-9',
    description: 'ANTIOXIDANT FACE SERUM - Vitamin C blends with Botanical Hyaluronic Acid, Vitamin E, Witch Hazel, and Jojoba Oil to promote your skins response to signs of aging like brightness, wrinkles, & dark spots',
    category: 1,
  },
  {
    id: 3,

    name: 'Neutrogena Hydro Boost Hyaluronic Acid',
    img: 'https://m.media-amazon.com/images/I/71Bd6+BQQnL._AC_UL480_QL65_.jpg',
    gal1: 'https://m.media-amazon.com/images/I/71Bd6+BQQnL._AC_UL480_QL65_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/81lnbAxwe2L._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/81ULS%2BLr8SL._SL1500_.jpg',
    price: 16.97,
    rating: 4.5,
    link: 'https://www.amazon.com/Neutrogena-Hydro-Hyaluronic-Hydrating-Moisturizer/dp/B00NR1YQHM/ref=sr_1_17?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-17',
    description: '1.7-fluid ounce jar of Neutrogena Hydro Boost hydrating water-gel face moisturizer with hyaluronic acid to hydrate dry skin',
    category: 1,
  },

  {
    id: 4,

    name: 'Weleda Skin Food Original Ultra-Rich Body Cream',
    img: 'https://m.media-amazon.com/images/I/71keoBqoiYL._AC_UL480_QL65_.jpg',
    gal1: 'https://m.media-amazon.com/images/I/71keoBqoiYL._AC_UL480_QL65_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/81YAH1vge%2BL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71SHtxvUjbL._SL1500_.jpg',
    price: 17.96,
    rating: 4.35,
    link: 'https://www.amazon.com/Weleda-Skin-Food-2-5-Ounce/dp/B000ORV3NC/ref=sr_1_37?dchild=1&qid=1614153279&s=beauty-intl-ship&sr=1-37',
    description: 'Skin Food is a universal savior of dry, rough skin on faces, elbows, hands and feet.',
    category: 1,
  },
  {
    id: 5,

    name: 'TruSkin Vitamin C Serum for Face, Topical Facial Serum',
    img: 'https://images-na.ssl-images-amazon.com/images/I/516yN4iPdQL._SL1250_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/81ELVWF0f6L._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71eviHyiO2L._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/718xQxTPqKL._SL1500_.jpg',
    price: 19.99,
    rating: 4.3,
    link: 'https://www.amazon.com/TruSkin-Naturals-Vitamin-Topical-Hyaluronic/dp/B01M4MCUAF/ref=sr_1_1_sspa?dchild=1&keywords=skin+care&qid=1619081546&s=beauty-intl-ship&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExSFVHRkhWREdQWlRDJmVuY3J5cHRlZElkPUEwNjA0MDMwMklGNFhXNlFZSVhLNiZlbmNyeXB0ZWRBZElkPUEwNzk2MTI0MThaVzVBWThWMThFMSZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=',
    description: 'ANTIOXIDANT FACE SERUM - Vitamin C blends with Botanical Hyaluronic Acid, Vitamin E, Witch Hazel, and Jojoba Oil to promote your skin\'s response to signs of aging like brightness, wrinkles, & dark spots',
    category: 1,
  },
  {
    id: 6,

    name: 'Bio-Oil Skincare Oil, Body Oil ',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71NAZ7a2iWL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/61opudsdSAL._SL1125_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/716JRqTRmaL._SL1125_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71Xzj%2BXo3uL._SL1500_.jpg',
    price: 8.92,
    rating: 4.6,
    link: 'https://www.amazon.com/Bio-Oil-2oz-Multiuse-Skincare-Oil/dp/B000VPPUEA/ref=sr_1_2?dchild=1&keywords=skin+care&qid=1619081816&s=beauty-intl-ship&sr=1-2',
    description: 'IMPROVES APPEARANCE OF ACNE SCARS AND STRETCH MARKS - Clinically proven to help repair skin damage and scars from pregnancy, surgery, injury, acne, C-section, aging, and more.',
    category: 1,
  },
  {
    id: 7,

    name: 'New York Biology Dead Sea Mud Mask for Face and Body ',
    img: 'https://images-na.ssl-images-amazon.com/images/I/81UYOXNTqIL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/81rOmGYQDRL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/61q7wnXKz-L._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61z6cdp7mjL._SL1500_.jpg',
    price: 14.95,
    rating: 4.5,
    link: 'https://www.amazon.com/Dead-Sea-Mask-Face-Body/dp/B01NCM25K7/ref=sr_1_3?dchild=1&keywords=skin+care&qid=1619081816&s=beauty-intl-ship&sr=1-3',
    description: 'Works for all skin types, including dry, normal, oily, combination, sensitive, and irritated. This daily acne treatment has been designed to be highly effective yet gentle enough for everyday use and is a great gift for the holidays 2020.',
    category: 1,
  },


  {
    id: 8,
    name: 'IT Cosmetics Hello Lashes 5-in-1 Mascara',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71J9jhKf9UL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/81ttOXOU45L._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71qGaPFvIeL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71Km6fPUhGL._SL1500_.jpg',
    price: 23.36,
    rating: 4.5,
    link: 'https://www.amazon.com/Cosmetics-Hello-Lashes-Volumizing-Mascara/dp/B006GSPDVG/ref=sr_1_8?dchild=1&keywords=cosmetics+for+lashes&qid=1619082166&sr=8-8',
    description: '5-IN-1 FORMULA - Hello Lashes is a volumizing mascara, conditioning lash primer, lash-enhancing serum, lash tint and lash curler/comb—all in one!',
    category: 2,
  },
  {
    id: 9,
    name: 'Benefit Cosmetics Roller Lash Curling & Lifting Mascara ',
    img: 'https://images-na.ssl-images-amazon.com/images/I/31RxVswbmuL.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/41OqZlMCzTL.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/41m0hB4PIUL.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/31njUVwvhPL.jpg',
    price: 24.38,
    rating: 4.7,
    link: 'https://www.amazon.com/Benefit-Cosmetics-Curling-Lifting-Mascara/dp/B07167RSXS/ref=sr_1_15?dchild=1&keywords=cosmetics+for+lashes&qid=1619082349&sr=8-15',
    description: 'NATURAL & HYPOALLERGENIC---Made with natural/non-toxic ingredients, the mascara will not cause irritation. The powerful formula is yet gentle enough for any skin type.',
    category: 2,
  },

  {
    id: 10,
    name: 'Makeup Remover ',
    img: 'https://m.media-amazon.com/images/I/81z8tQe35hL._AC_UL480_QL65_.jpg',
    gal1: 'https://m.media-amazon.com/images/I/81z8tQe35hL._AC_UL480_QL65_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/81ZimLGwwaL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71i0OWKabvL._SL1500_.jpg',
    price: 11.96,
    rating: 4.5,
    link: 'https://www.amazon.com/Neutrogena-Makeup-Removing-Wipes-Count/dp/B00U2VQZDS/ref=sr_1_4?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-4',
    description: 'Twin pack of 25 count soft, pre-moistened Neutrogena Makeup Remover Cleansing Face Wipes to remove makeup and effectively cleanse skin in 1 easy step',
    category: 2,
  },
  {
    id: 11,
    name: 'essence | Disney Princess Collection',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71rxk0l1dZL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/71OOmy3YraL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/81P4Fm0onYL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/81tIJgUe2QL._SL1500_.jpg',
    price: 4.99,
    rating: 4.4,
    link: 'https://www.amazon.com/essence-Princess-Collection-Mascara-Waterproof/dp/B08TC82LCT/ref=sr_1_9?dchild=1&keywords=cosmetics+for+lashes&qid=1619082349&sr=8-9',
    description: 'ENCHANTED LASHES: travel under the sea with the essence x Disney Princess Collection Lash Princess Ariel False Lash Effect Waterproof mascara. The same essence Lash Princess False Lash Waterproof mascara formula, but in a mermaid-approved version with a limited edition Ariel princess illustration.',
    category: 2,
  },
  {
    id: 12,
    name: '4D Silk Lash Fiber Mascara Makeup',
    img: 'https://images-na.ssl-images-amazon.com/images/I/61liWd8qFhL._SL1000_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/61jkXSLSWfL._SL1000_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71gIYQWk59L._SL1000_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61uPixGCjuL._SL1000_.jpg',
    price: 6.99,
    rating: 2.2,
    link: 'https://www.amazon.com/dp/B087C4VLFS/ref=sspa_dk_detail_5?psc=1&pd_rd_i=B087C4VLFS&pd_rd_w=ZM7bS&pf_rd_p=085568d9-3b13-4ac1-8ae4-24a26c00cb0c&pd_rd_wg=ReyYG&pf_rd_r=65PJBG1VWN5FKJ1Y544H&pd_rd_r=87a11cbd-046a-4faa-b88a-b3af85bd2b96&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFUTklRNTBFQUxRRUkmZW5jcnlwdGVkSWQ9QTA4NzUxMjgxSDVXSVBWNU5QRFpHJmVuY3J5cHRlZEFkSWQ9QTA1MzU3NDYyWE43VDIxVzhOSlYmd2lkZ2V0TmFtZT1zcF9kZXRhaWwmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl',
    description: 'Waterproof and Smude-Proof - This formula can keep perfect makeup all day',
    category: 2,
  },
  {
    id: 13,
    name: 'SIAMHOO 2PCS 4D Silk Fiber Lash Mascara Waterproof Mascara',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71WKz2QTHPL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/71VIfQ6NEfL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71lYam7XHXL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/81E93%2BfDjVL._SL1500_.jpg',
    price: 9.99,
    rating: 4.2,
    link: 'https://www.amazon.com/dp/B089SW3QXR/ref=sspa_dk_detail_3?psc=1&pd_rd_i=B089SW3QXR&pd_rd_w=mQSPK&pf_rd_p=085568d9-3b13-4ac1-8ae4-24a26c00cb0c&pd_rd_wg=ZGrAr&pf_rd_r=0GQDDF7GM9KS2XH3HGV1&pd_rd_r=df494ff6-1460-4a36-8f04-344d71ab19f3&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFPU0xWNkRZOTdNTVgmZW5jcnlwdGVkSWQ9QTAyMTUzODEzNU1NUEJXRFM4MUJXJmVuY3J5cHRlZEFkSWQ9QTA5NDE0NjExR09TUUkwVlRGVkNYJndpZGdldE5hbWU9c3BfZGV0YWlsJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==',
    description: 'Sensitive Skin Care: this black mascara is made of natural and non-toxic ingredients, safe for sensitive eyes and contact lens wearers',
    category: 2,
  },
  {
    id: 14,
    name: 'Maybelline Lash Sensational Washable Mascara',
    img: 'https://images-na.ssl-images-amazon.com/images/I/61OFOt%2B7PxL._SL1000_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/71cyLgr7LZL._SL1000_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/61SCm%2BpBezL._SL1000_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71TkhceBthL._SL1000_.jpg',
    price: 12.99,
    rating: 4.5,
    link: 'https://www.amazon.com/Maybelline-Sensational-Washable-Mascara-Blackest/dp/B07HM9ZWKM/ref=sr_1_26?dchild=1&keywords=cosmetics+for+lashes&qid=1619082349&sr=8-26',
    description: 'Lash Sensational, For A Full Fan Effect: Exclusive fanning mascara brush with ten layers of bristles reveals layers of lashes for a sensational full-fan effect; Add the look of length and volume without clumping; Ophthalmologist tested, contact lens safe',
    category: 2,
  },


  {
    id: 15,
    name: 'Castor Oil USDA Organic Cold-Pressed ',
    img: 'https://images-na.ssl-images-amazon.com/images/I/619r4HOkWSL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/417ftdJbkTL.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/81BrKidFEIL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/81JszewoSML._SL1500_.jpg',
    price: 16.95,
    rating: 4.6,
    link: 'https://www.amazon.com/Castor-16oz-Organic-Cold-Pressed-Hexane-Free/dp/B0186U9736/ref=sr_1_4?dchild=1&keywords=hair+care&qid=1619083271&sr=8-4',
    description: '100% Pure and Cold-pressed: Sky Organics 100% pure, unrefined Castor Oil contains no added ingredients, fragrance, alcohols, or preservatives.',
    category: 3,
  },
  {
    id: 16,
    name: 'Herstyler Hair Repair Serum - Argan Oil Hair Serum',
    img: 'https://images-na.ssl-images-amazon.com/images/I/61QLCOJdi7L._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/71KnVox6lPL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/81FrsL9aGOL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71T6BGGp4%2BL._SL1500_.jpg',
    price: 11.99,
    rating: 4.4,
    link: 'https://www.amazon.com/Herstyler-Hair-Serum-Vitamin-Straightening/dp/B00BC3YL2W/ref=sr_1_7?dchild=1&keywords=hair+care&qid=1619083569&sr=8-7',
    description: 'MANE MAKEOVER - This hair shine serum transforms dry, damaged hair leaving it lush and glossy. What’s more is that this frizz control hair product works well on straight or curly hair.',
    category: 3,
  },
  {
    id: 17,
    name: 'Castor Oil (2oz) USDA Certified Organic',
    img: 'https://m.media-amazon.com/images/I/615AiiiHAUL._AC_UL480_QL65_.jpg',
    gal1: 'https://m.media-amazon.com/images/I/615AiiiHAUL._AC_UL480_QL65_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71Yo6DxPm0L._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71lHRBvuRLL._SL1500_.jpg',
    price: 9.99,
    rating: 4.67,
    link: 'https://www.amazon.com/Certified-Kate-Stimulate-Eyelashes-Treatment/dp/B01NALN8Q9/ref=sr_1_32?dchild=1&qid=1614153279&s=beauty-intl-ship&sr=1-32',
    description: 'USDA CERTIFIED ORGANIC CASTOR OIL - Kate Blanc’s Organic Cold Pressed Castor Oil is certified by USDA and is guaranteed to be authentic, pure, natural, and hexane free. 100% Authentic or Full Refund.',
    category: 3,
  },
  {
    id: 18,
    name: 'Era Organics Hair Conditioner For Dry Hair ',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71s1CL20EuL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/91qzVy27ugL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/81k0H5hlOFL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/91odWEM-myL._SL1500_.jpg',
    price: 15.45,
    rating: 4.1,
    link: 'https://www.amazon.com/dp/B075F9RX5P?pd_rd_i=B075F9RX5P&pd_rd_w=LsSnY&pf_rd_p=3465d0d7-4e28-4692-b633-326c458deaa4&pd_rd_wg=t32pS&pf_rd_r=7ZQR77A8XA36XM75V6GG&pd_rd_r=50bc52ea-bf7e-4573-bc25-4e713c1ba248',
    description: 'Premium Hair Conditioner Perfect for Dry, Damaged, Frizzy Hair Salon quality plant based formula with ingredients proven to give you stronger, healthier, more luxurious hair. Say goodbye to brittle, frizzy, unmanageable dry hair.',
    category: 3,
  },
  {
    id: 19,
    name: 'Voir Haircare, Rhythm of th Rain Hair Masque & Scalp Detox',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71beTcf1QvL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/71picKNoH0L._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71CajGeK%2BWL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/81XFlJpWqGL._SL1500_.jpg',
    price: 28,
    rating: 4.7,
    link: 'https://www.amazon.com/Voir-Natural-Masque-Scalp-Rhythm/dp/B07572XFXS/ref=sr_1_10?dchild=1&keywords=hair+care&qid=1619083569&sr=8-10',
    description: '3-MINUTE MOISTURE MAGIC, A creamy, thirst-quenching hair masque that restores scalp health and leaves hair feeling soft, silky and magnificently moisturized.',
    category: 3,
  },
  {
    id: 20,
    name: 'Loma Hair Care Nourishing Oil Treatment',
    img: 'https://images-na.ssl-images-amazon.com/images/I/61C3SVQ8pXL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/610vZP%2BsxYL._SL1010_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/61IqbvWOTzL._SL1000_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/6159G4wsS%2BL._SL1000_.jpg',
    price: 25,
    rating: 4.8,
    link: 'https://www.amazon.com/Loma-Hair-Care-Nourishing-Treatment/dp/B00GLICF9O/ref=sr_1_15?dchild=1&keywords=hair+care&qid=1619083569&sr=8-15',
    description: 'A Nourishing Oil Treatment for complete thermal protection, and humidity resistance for all hair types.',
    category: 3,
  },
  {
    id: 21,
    name: 'Cliganic USDA Organic Castor Oil',
    img: 'https://images-na.ssl-images-amazon.com/images/I/81t4gKczC%2BL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/81S4c3IqguL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/41bUxwU3peL.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61nTT290xdL._SL1118_.jpg',
    price: 9.99,
    rating: 4.5,
    link: 'https://www.amazon.com/Cliganic-Eyelashes-Eyebrows-Unrefined-Hexane-Free/dp/B07Z55TTHR/ref=sr_1_27_sspa?dchild=1&keywords=hair+care&qid=1619083569&sr=8-27-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFDN1ZXVFlQUUM2Sk8mZW5jcnlwdGVkSWQ9QTA4NzE5MzlJVDhZTUJPRTAzUFYmZW5jcnlwdGVkQWRJZD1BMDU4MTgzNTFYMjU4M1NONEtES1kmd2lkZ2V0TmFtZT1zcF9tdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl',
    description: 'USDA CERTIFIED ORGANIC CASTOR OIL - the strict oversight of USDA ensures the integrity of our Organic Cold Pressed Castor Oil. In other words, it’s really 100% ORGANIC.',
    category: 3,
  },

  {
    id: 22,
    name: 'Dove Body Wash',
    img: 'https://m.media-amazon.com/images/I/71NbfFpRvzL._AC_UL480_QL65_.jpg',
    gal1: 'https://m.media-amazon.com/images/I/71NbfFpRvzL._AC_UL480_QL65_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/81JFz0S791L._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/81c7wVTytuL._SL1500_.jpg',
    price: 12.09,
    rating: 4.0,
    link: 'https://www.amazon.com/Dove-Body-Wash-Pump-Moisture/dp/B00MEDOY2G/ref=sr_1_15?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-15',
    description: 'Dove Deep Moisture Body Wash is Just As Effective for Cleaning Hands!',
    category: 4,
  },
  {
    id: 23,
    name: 'Aveeno Stress Relief Body Wash with Soothing Oat, Lavender, Chamomile & Ylang-Ylang Essential Oils',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71MEiCIwNwL._SL1500_.jpghttps://images-na.ssl-images-amazon.com/images/I/71MEiCIwNwL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/71JoQxVi-vL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71CWjss9pBL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71sHbWgYGNL._SL1500_.jpg',
    price: 7.17,
    rating: 4.7,
    link: 'https://www.amazon.com/Aveeno-Chamomile-Ylang-Ylang-Essential-Hypoallergenic/dp/B07FK8YR27/ref=sr_1_1_sspa?crid=1HKCZANPW8DT6&dchild=1&keywords=body+wash&qid=1619084854&sprefix=body%2Caps%2C341&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyMFoxVEZNUTFTSE5JJmVuY3J5cHRlZElkPUEwNjQ1OTU1MllMMDkzTVUyR0dMRCZlbmNyeXB0ZWRBZElkPUEwNTEzNjE0QTY0NE5ZSU5ZVTBXJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==',
    description: '18-fluid ounces of Aveeno Stress Relief Body Wash with calming lavender scent gently cleanses while removing dirt, oil and bacteria',
    category: 4,
  },
  {
    id: 24,
    name: 'Old Spice Hydro Body Wash for Men',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71h41TqgDPL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/81hIvz9pcsL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/81Y-LXYkRXL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/A1x1yOlM83L._SL1500_.jpg',
    price: 19.94,
    rating: 4.7,
    link: 'https://www.amazon.com/Old-Spice-Smoother-Swagger-Collection/dp/B078J7PNSS/ref=sr_1_3_sspa?crid=1HKCZANPW8DT6&dchild=1&keywords=body+wash&qid=1619085002&sprefix=body%2Caps%2C341&sr=8-3-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyVk1OQlhZNlZMNVdPJmVuY3J5cHRlZElkPUEwMTI1MTM2OE1ITUFFTDA5T081JmVuY3J5cHRlZEFkSWQ9QTA0MDk5MjgyR1BKNFpQNFMxQU1BJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==',
    description: 'Smoother Swagger is a fresh and frisky merger of pure success and hints of crisp apple and fresh herbs',
    category: 4,
  },
  {
    id: 25,
    name: 'Weleda Skin Food Original Ultra-Rich Body Cream',
    img: 'https://m.media-amazon.com/images/I/71keoBqoiYL._AC_UL480_QL65_.jpg',
    gal1: 'https://m.media-amazon.com/images/I/71keoBqoiYL._AC_UL480_QL65_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/81YAH1vge%2BL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71SHtxvUjbL._SL1500_.jpg',
    price: 17.96,
    rating: 4.35,
    link: 'https://www.amazon.com/Weleda-Skin-Food-2-5-Ounce/dp/B000ORV3NC/ref=sr_1_37?dchild=1&qid=1614153279&s=beauty-intl-ship&sr=1-37',
    description: 'Skin Food is a universal savior of dry, rough skin on faces, elbows, hands and feet.',
    category: 4,
  },
  {
    id: 26,
    name: 'Everyone 3-in-1 Soap: Shampoo,Body Wash, Bubble Bath',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71PrOczB0FL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/71pWNOIzhvL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/819eQKwo0rL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71YznQvdR5L._SL1500_.jpg',
    price: 18.16,
    rating: 4.7,
    link: 'https://www.amazon.com/dp/B00L7S3FDI?pd_rd_i=B00L7S3FDI&pd_rd_w=IQ1PB&pf_rd_p=3465d0d7-4e28-4692-b633-326c458deaa4&pd_rd_wg=cprUI&pf_rd_r=CJS5XM560SRJX3D050FB&pd_rd_r=60cc6d84-2ebf-48cc-ad7e-3e5134e6b5f8',
    description: 'The relaxing scent of lavender is blended with refreshing aloe pure essential oil in this skin-nourishing soap that works great as a body wash, shampoo, and bubble bath',
    category: 4,
  },
  {
    id: 27,
    name: ' Solimo Shea Butter and Oatmeal Body Wash',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71o6c41F2NL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/71MU071RRBL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/61a-cdh8WOL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61KSNoS43cL._SL1500_.jpg',
    price: 4.41,
    rating: 4.6,
    link: 'https://www.amazon.com/Amazon-Brand-Solimo-Butter-Oatmeal/dp/B07NJNZYQT/ref=sxin_10_trfob_2?crid=1HKCZANPW8DT6&cv_ct_cx=body+wash&dchild=1&keywords=body+wash&pd_rd_i=B07NJNZYQT&pd_rd_r=60cc6d84-2ebf-48cc-ad7e-3e5134e6b5f8&pd_rd_w=SLJcV&pd_rd_wg=cprUI&pf_rd_p=6c6f0ed1-2306-4f6f-832e-d796b7d41a25&pf_rd_r=CJS5XM560SRJX3D050FB&qid=1619085002&sprefix=body%2Caps%2C341&sr=1-3-fcc74f9e-0165-48d2-a9e1-f41ea92a035c',
    description: 'Hypoallergenic body wash helps cleanse and moisturize dry skin in the bath or shower',
    category: 4,
  },
  {
    id: 28,
    name: 'SheaMoisture African Black Soap Body Wash',
    img: 'https://images-na.ssl-images-amazon.com/images/I/817n7Wc%2Bw0L._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/611qRJvr6aL._SL1000_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/91ynokHLSnL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/91RjnR2RanL._SL1500_.jpg',
    price: 19.99,
    rating: 4.7,
    link: 'https://www.amazon.com/SheaMoisture-African-Black-Soap-Body/dp/B01FT1FL3K/ref=sxin_11?asc_contentid=amzn1.osa.6f4bc4d8-49a0-4c91-ada7-4bd70e978831.ATVPDKIKX0DER.en_US&asc_contenttype=article&ascsubtag=amzn1.osa.6f4bc4d8-49a0-4c91-ada7-4bd70e978831.ATVPDKIKX0DER.en_US&creativeASIN=B01FT1FL3K&crid=1HKCZANPW8DT6&cv_ct_cx=body+wash&cv_ct_id=amzn1.osa.6f4bc4d8-49a0-4c91-ada7-4bd70e978831.ATVPDKIKX0DER.en_US&cv_ct_pg=search&cv_ct_we=asin&cv_ct_wn=osp-single-source-earns-comm&dchild=1&keywords=body+wash&linkCode=oas&pd_rd_i=B01FT1FL3K&pd_rd_r=60cc6d84-2ebf-48cc-ad7e-3e5134e6b5f8&pd_rd_w=MMpAs&pd_rd_wg=cprUI&pf_rd_p=97edcd33-ae52-416a-820f-978f86b3258a&pf_rd_r=CJS5XM560SRJX3D050FB&qid=1619085002&sprefix=body%2Caps%2C341&sr=1-1-64f3a41a-73ca-403a-923c-8152c45485fe&tag=scripps-bounce-20',
    description: 'ANTI-BACTERIAL: This All Natural And Organic Body Wash Controls Acne With The Anti-Bacterial Properties Of African Black Soap',
    category: 4,
  },
  {
    id: 29,
    name: 'Anastasia Beverly Hills - Brow Wiz',
    img: 'https://images-na.ssl-images-amazon.com/images/I/415UfCqxrYL._SL1000_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/415UfCqxrYL._SL1000_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/31M1MrF1FzL.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/51RNi3vOx4L.jpg',
    price: 9.57,
    rating: 4.8,
    link: 'https://www.amazon.com/Burts-Bees-Natural-Moisturizing-Multipack/dp/B01MRH7MR4/ref=sxin_10?asc_contentid=amzn1.osa.d02b20ed-78c1-4525-bc07-eb5f0e238350.ATVPDKIKX0DER.en_US&asc_contenttype=article&ascsubtag=amzn1.osa.d02b20ed-78c1-4525-bc07-eb5f0e238350.ATVPDKIKX0DER.en_US&creativeASIN=B01MRH7MR4&crid=HRLV59Z2NHBP&cv_ct_cx=lip+balm&cv_ct_id=amzn1.osa.d02b20ed-78c1-4525-bc07-eb5f0e238350.ATVPDKIKX0DER.en_US&cv_ct_pg=search&cv_ct_we=asin&cv_ct_wn=osp-single-source-earns-comm&dchild=1&keywords=lip+balm&linkCode=oas&pd_rd_i=B01MRH7MR4&pd_rd_r=a55cfdb4-c6f8-4e20-8351-4370764d0ac7&pd_rd_w=StX73&pd_rd_wg=XzMG1&pf_rd_p=97edcd33-ae52-416a-820f-978f86b3258a&pf_rd_r=SR7W8ST6A0JEMRJFFR5D&qid=1619084968&sprefix=lip+balm,aps,501&sr=1-1-64f3a41a-73ca-403a-923c-8152c45485fe&tag=scripps-bounce-20',
    description: 'An ultra-slim, retractable pencil used to outline and fill in brows. Perfect tool for outlining brows and adding precise detail. For Medium Brown hair with cool/ash undertones.',
    category: 5,
  },
  {
    id: 30,
    name: 'NYX PROFESSIONAL MAKEUP Tinted Brow Mascara',
    img: 'https://images-na.ssl-images-amazon.com/images/I/51mNv-ZsPbL._SL1000_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/51mNv-ZsPbL._SL1000_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/61IaJWOldxL._SL1000_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61lu8OeDnKL._SL1500_.jpg',
    price: 6.99,
    rating: 4.4,
    link: 'https://www.amazon.com/NYX-PROFESSIONAL-MAKEUP-Mascara-Brunette/dp/B00P1HO2BU/ref=sr_1_7?dchild=1&keywords=brow&qid=1619086986&sr=8-7',
    description: 'TINTED BROW MASCARA: Tame, tint, fill and set eyebrows in one step with our Tinted Brow Mascara',
    category: 5,
  },
  {
    id: 31,
    name: 'Eyebrow Soap, 3D Brows Styling Soap',
    img: 'https://images-na.ssl-images-amazon.com/images/I/61N1BO+XR3L._SL1001_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/61N1BO+XR3L._SL1001_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/61L2sbWQGjL._SL1001_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61OYHUlHi4L._SL1001_.jpg',
    price: 5.99,
    rating: 4.2,
    link: 'https://www.amazon.com/Eyebrow-Styling-Transparent-Lasting-Natural/dp/B08FJ3DR81/ref=sr_1_15?dchild=1&keywords=brow&qid=1619086986&sr=8-15',
    description: 'Three-dimensional eyebrow: The 3D eyebrow soap has a uniform texture, which can create 3D natural and perfect eyebrows. Make your makeup more beautiful.',
    category: 5,
  },
  {
    id: 32,
    name: 'Brow Lamination Kit',
    img: 'https://images-na.ssl-images-amazon.com/images/I/51ZZbYawkOL._SL1000_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/51ZZbYawkOL._SL1000_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/61FAS5u1eHL._SL1000_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/512agcVnjiL._SL1000_.jpg',
    price: 24.99,
    rating: 4.6,
    link: 'https://www.amazon.com/Lamination-ANNATATO-Professional-Duration-Suitable/dp/B08HGV9D7X/ref=sr_1_10?dchild=1&keywords=brow&qid=1619086986&sr=8-10',
    description: 'Brow Lamination Kit: ANNATATO eyebrow lift/lamination kit specifically formulated to enhance, lift and add more glamour and character to your brows.',
    category: 5,
  },
  {
    id: 33,
    name: 'Maybelline New York TattooStudio Brow Tint Pen',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71vhSkprbRL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/71vhSkprbRL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/81BEddhNk1L._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71s24q4AtfL._SL1500_.jpg',
    price: 7.50,
    rating: 3.7,
    link: 'https://www.amazon.com/Maybelline-TattooStudio-Makeup-Brown-0-037/dp/B07BHB7PN5/ref=sr_1_27?dchild=1&keywords=brow&qid=1619086986&sr=8-27',
    description: 'Create hair-like strokes with ease for filled, natural-looking eyebrows with this natural tattoo eyebrow pen; Our exclusively designed multi-prong tip creates the look of naturally filled eyebrows',
    category: 5,
  },
  {
    id: 34,
    name: 'Benefit Precisely My Brow Pencil ',
    img: 'https://images-na.ssl-images-amazon.com/images/I/61qzxlNz8WL._SL1000_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/61qzxlNz8WL._SL1000_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71i+LNBb46L._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61ntACR3caL._SL1500_.jpg',
    price: 16.14,
    rating: 4.7,
    link: 'https://www.amazon.com/Benefit-Precisely-Pencil-Ultra-Defining/dp/B01HN51UL2/ref=sr_1_25?dchild=1&keywords=brow&qid=1619086986&sr=8-25',
    description: 'A few strokes of the rich yet blendable color will transform brows from shapeless & undefined to filled & defined eyebrows.',
    category: 5,
  },
  {
    id: 35,
    name: 'NYX PROFESSIONAL MAKEUP The Brow Glue Instant Brow Styler',
    img: 'https://images-na.ssl-images-amazon.com/images/I/71dXKKZevrL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/71dXKKZevrL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/61YqqfSB0yL._SL1000_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61SeAaV8dAL._SL1000_.jpg',
    price: 7.97,
    rating: 4.2,
    link: 'https://www.amazon.com/NYX-PROFESSIONAL-MAKEUP-Instant-Styler/dp/B08M58SWB1/ref=sr_1_38?dchild=1&keywords=brow&qid=1619086986&sr=8-38',
    description: 'nstant Brow Styler: This non sticky and transparent brow glue gives you extra strong, 16 hour extreme hold instantly, allowing you to style brow hairs and hold them in place for limitless looks',
    category: 5,
  },
  {
    id: 36,
    name: 'NYX PROFESSIONAL MAKEUP Matte Lipstick - Perfect Red',
    img: 'https://m.media-amazon.com/images/I/51cx9tBNaRL._AC_UL320_.jpg',
    gal1: 'https://m.media-amazon.com/images/I/51cx9tBNaRL._AC_UL320_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/51qkxXVHg+L._SL1001_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61zci3jj2-L._SL1001_.jpg',
    price: 6.00,
    rating: 4.4,
    link: 'https://www.amazon.com/NYX-Matte-Lipstick-Perfect-Red/dp/B005FYJD7M/ref=sr_1_8?crid=2Q3Y1G6N488XS&dchild=1&keywords=lipstick&qid=1619081180&s=beauty-intl-ship&sprefix=lip,beauty-intl-ship,549&sr=1-8',
    description: 'Smooth and Plush Matte Lipstick: Load your lips with the plush, pigment rich matte colors of this shockingly smooth matte lipstick that glides right on and stays in place with a silky matte finish.',
    category: 6,
  },
  {
    id: 37,
    name: 'Maybelline SuperStay Matte Ink Liquid Lipstick',
    img: 'https://images-na.ssl-images-amazon.com/images/I/61PPci2flAL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/61PPci2flAL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71DNP2yJfDL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71tRC70uMVL._SL1500_.jpg',
    price: 7.50,
    rating: 4.4,
    link: 'https://www.amazon.com/Maybelline-SuperStay-Liquid-Lipstick-Loyalist/dp/B06XDX6YGK/ref=sr_1_11?crid=2AYPOJCUQ7384&dchild=1&keywords=lipstick+kylie&qid=1619082608&sprefix=lipstick+ky,beauty-intl-ship,355&sr=8-11',
    description: 'ALL DAY MATTE LIPSTICK: This highly pigmented matte liquid lipstick goes on smooth, lasts up to 16 hours, and is available in a range of super saturated shades including nude shades to classic Red lipstick. Ink your lips in gorgeous, matte lip color.',
    category: 6,
  },
  {
    id: 38,
    name: 'Lip Lacquer, Moisturizing, Shiny, Non-Sticky, Long Lasting',
    img: 'https://images-na.ssl-images-amazon.com/images/I/61OG9bzS9XL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/61OG9bzS9XL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/612nMcHOTmL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/71mNwY2CaWL._SL1500_.jpg',
    price: 3.00,
    rating: 4.5,
    link: 'https://www.amazon.com/Lacquer-Moisturizing-Non-Sticky-Lasting-Provides/dp/B085P21LC3/ref=sr_1_5?crid=2DZV5ND96H4W9&dchild=1&keywords=lip+gloss&qid=1619082998&sprefix=lip,aps,374&sr=8-5',
    description: 'Formulated with vitamin e to moisturize lips, providing maximum colour and brilliant shine.',
    category: 6,
  },
  {
    id: 39,
    name: 'Broadway Vita-Lip Clear Lip Gloss ',
    img: 'https://images-na.ssl-images-amazon.com/images/I/61cBW1pVO6L._SL1000_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/61cBW1pVO6L._SL1000_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/61cBW1pVO6L._SL1000_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61cBW1pVO6L._SL1000_.jpg',
    price: 3.95,
    rating: 4.5,
    link: 'https://www.amazon.com/Broadway-Vita-Lip-Clear-Gloss-0-47oz/dp/B074BFF9P6/ref=sr_1_4?crid=2DZV5ND96H4W9&dchild=1&keywords=lip+gloss&qid=1619083643&sprefix=lip,aps,374&sr=8-4',
    description: 'Rosehip Oil - Reduces Fine Lines on Lips, Moisturizes & Heals and Contains Vitamin A.',
    category: 6,
  },
  {
    id: 40,
    name: 'Rare Beauty Mini Lip Souffle Mat Lip Cream Duo',
    img: 'https://cdn.shopify.com/s/files/1/0314/1143/7703/products/lip-souffle-2piece-sku-2.jpg?v=1602106610',
    gal1: 'https://cdn.shopify.com/s/files/1/0314/1143/7703/products/lip-souffle-2piece-sku-2.jpg?v=1602106610',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/41oehoabPhL.jpg',
    gal3: 'https://cdn.shopify.com/s/files/1/0314/1143/7703/products/lip-souffle-2piece-sku-1.jpg?v=1602106610',
    price: 24.05,
    rating: 4.5,
    link: 'https://www.amazon.com/Rare-Beauty-Mini-Souffle-Cream/dp/B08MK66G8K/ref=sr_1_1?crid=1GGPV1VTQ4YXB&dchild=1&keywords=rare+beauty+lipstick&qid=1619084231&sprefix=rare+beauty+l%2Caps%2C392&sr=8-1',
    description: 'Limited Edition: A travel-size duo of mini Lip Soufflé Matte Lip Creams in bestselling shades Inspire—Selena’s signature red!—and Fearless, a deep mauve rose.',
    category: 6,
  },
  {
    id: 41,
    name: 'NYX PROFESSIONAL MAKEUP Slim Lip Pencil',
    img: 'https://images-na.ssl-images-amazon.com/images/I/513vqPXKUCL._SL1000_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/513vqPXKUCL._SL1000_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71Cbun4vchL._SL1000_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/61DCEShk2LL._SL1000_.jpg',
    price: 3.79,
    rating: 4.5,
    link: 'https://www.amazon.com/NYX-PROFESSIONAL-MAKEUP-Pencil-Ounce/dp/B07B16318X/ref=sr_1_1_sspa?crid=2QBDC0FLR9DFC&dchild=1&keywords=lip+liner&qid=1619084746&sprefix=lip,aps,354&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyVU9GOFkyRTI0WjFaJmVuY3J5cHRlZElkPUEwNTYyMDEzMUI3VTNGQUpYTVpWNCZlbmNyeXB0ZWRBZElkPUEwMTAxNjA2MVVINzZBQVpKODY5SyZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=',
    description: 'LIP LINER IN ALL SHADES: NYX Professional Makeup Slim Lip Pencil natural lip liner pencils come in a variety of dashing shades from auburn to orange and traffic-stopping red to line and define your lips',
    category: 6,
  },
  {
    id: 42,
    name: 'Burts Bees 100% Natural Origin Lip Balm',
    img: 'https://images-na.ssl-images-amazon.com/images/I/716hTRmY8HL._SL1500_.jpg',
    gal1: 'https://images-na.ssl-images-amazon.com/images/I/716hTRmY8HL._SL1500_.jpg',
    gal2: 'https://images-na.ssl-images-amazon.com/images/I/71YdCv8bqXL._SL1500_.jpg',
    gal3: 'https://images-na.ssl-images-amazon.com/images/I/718-mTQSiWL._SL1500_.jpg',
    price: 9.57,
    rating: 4.8,
    link: 'https://www.amazon.com/Burts-Bees-Natural-Moisturizing-Multipack/dp/B01MRH7MR4/ref=sxin_10?asc_contentid=amzn1.osa.d02b20ed-78c1-4525-bc07-eb5f0e238350.ATVPDKIKX0DER.en_US&asc_contenttype=article&ascsubtag=amzn1.osa.d02b20ed-78c1-4525-bc07-eb5f0e238350.ATVPDKIKX0DER.en_US&creativeASIN=B01MRH7MR4&crid=HRLV59Z2NHBP&cv_ct_cx=lip+balm&cv_ct_id=amzn1.osa.d02b20ed-78c1-4525-bc07-eb5f0e238350.ATVPDKIKX0DER.en_US&cv_ct_pg=search&cv_ct_we=asin&cv_ct_wn=osp-single-source-earns-comm&dchild=1&keywords=lip+balm&linkCode=oas&pd_rd_i=B01MRH7MR4&pd_rd_r=a55cfdb4-c6f8-4e20-8351-4370764d0ac7&pd_rd_w=StX73&pd_rd_wg=XzMG1&pf_rd_p=97edcd33-ae52-416a-820f-978f86b3258a&pf_rd_r=SR7W8ST6A0JEMRJFFR5D&qid=1619084968&sprefix=lip+balm,aps,501&sr=1-1-64f3a41a-73ca-403a-923c-8152c45485fe&tag=scripps-bounce-20',
    description: 'Lip CARE: Bursting with all natural flavors, refresh and nourish your lips with Burts Bees Moisturizing Lip Balm in four naturally Nourishing flavors: Original beeswax, strawberry, coconut & Pear and vanilla bean',
    category: 6,
  }
];
