import {category} from './category';
export const products = [
  {
    id: 1,

    name: 'CeraVe Moisturizing Cream ',
    img:"https://m.media-amazon.com/images/I/61S7BrCBj7L._AC_UL480_QL65_.jpg",
    gal1:"https://m.media-amazon.com/images/I/61S7BrCBj7L._AC_UL480_QL65_.jpg",
    gal2:"https://images-na.ssl-images-amazon.com/images/I/61lO1d7FSsL._SL1000_.jpg",
    gal3:"https://images-na.ssl-images-amazon.com/images/I/61RzTGeRKRL._SL1000_.jpg",
    price: 18.99,
    rating:4.9,
    link:"https://www.amazon.com/CeraVe-Moisturizing-Cream-Daily-Moisturizer/dp/B00TTD9BRC/ref=sr_1_2?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-2",
    description: 'With hyaluronic acid, ceramides and MVE technology for 24 hour hydration. Rich, velvety texture that leaves skin feeling smooth, it is absorbed quickly for softened skin without greasy, sticky, feel.',
    category: 1,
  },

  {
    id: 2,

    name: 'TruSkin Vitamin C Serum for Face',
    img:"https://m.media-amazon.com/images/I/516yN4iPdQL._AC_UL480_QL65_.jpg",
    gal1:"https://m.media-amazon.com/images/I/516yN4iPdQL._AC_UL480_QL65_.jpg",
    gal2:"https://images-na.ssl-images-amazon.com/images/I/71cDoRe7XkL._SL1500_.jpg",
    gal3:"https://images-na.ssl-images-amazon.com/images/I/51qwH8YGR9L.jpg",
    price: 29.99,
    rating:4.0,
    link:"https://www.amazon.com/TruSkin-Naturals-Vitamin-Topical-Hyaluronic/dp/B01M4MCUAF/ref=sr_1_9?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-9",
    description: 'ANTIOXIDANT FACE SERUM - Vitamin C blends with Botanical Hyaluronic Acid, Vitamin E, Witch Hazel, and Jojoba Oil to promote your skins response to signs of aging like brightness, wrinkles, & dark spots',
    category: 1,
  },
  {
    id: 3,

    name: 'Neutrogena Hydro Boost Hyaluronic Acid',
    img:"https://m.media-amazon.com/images/I/71Bd6+BQQnL._AC_UL480_QL65_.jpg",
    gal1:"https://m.media-amazon.com/images/I/71Bd6+BQQnL._AC_UL480_QL65_.jpg",
    gal2:"https://images-na.ssl-images-amazon.com/images/I/81lnbAxwe2L._SL1500_.jpg",
    gal3:"https://images-na.ssl-images-amazon.com/images/I/81ULS%2BLr8SL._SL1500_.jpg",
    price: 16.97,
    rating:4.5,
    link:"https://www.amazon.com/Neutrogena-Hydro-Hyaluronic-Hydrating-Moisturizer/dp/B00NR1YQHM/ref=sr_1_17?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-17",
    description: '1.7-fluid ounce jar of Neutrogena Hydro Boost hydrating water-gel face moisturizer with hyaluronic acid to hydrate dry skin',
    category: 1,
  },

  {
    id: 4,

    name: 'Weleda Skin Food Original Ultra-Rich Body Cream',
    img:"https://m.media-amazon.com/images/I/71keoBqoiYL._AC_UL480_QL65_.jpg",
    gal1:"https://m.media-amazon.com/images/I/71keoBqoiYL._AC_UL480_QL65_.jpg",
    gal2:"https://images-na.ssl-images-amazon.com/images/I/81YAH1vge%2BL._SL1500_.jpg",
    gal3:"https://images-na.ssl-images-amazon.com/images/I/71SHtxvUjbL._SL1500_.jpg",
    price: 17.96,
    rating:4.35,
    link:"https://www.amazon.com/Weleda-Skin-Food-2-5-Ounce/dp/B000ORV3NC/ref=sr_1_37?dchild=1&qid=1614153279&s=beauty-intl-ship&sr=1-37",
    description: 'Skin Food is a universal savior of dry, rough skin on faces, elbows, hands and feet.',
    category: 1,
  },

  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/71aPOVjcHpL._AC_UL480_QL65_.jpg",
    gal1: "https://m.media-amazon.com/images/I/71aPOVjcHpL._AC_UL480_QL65_.jpg",
    gal2: "https://images-na.ssl-images-amazon.com/images/I/91rRYi1mHGL._SL1500_.jpg",
    gal3: "https://images-na.ssl-images-amazon.com/images/I/81zjROIcmXL._SL1500_.jpg",
    name: 'Maybelline Sky High Washable Mascara',
    price: 12.5,
    rating:4.5,
    link:"https://www.amazon.com/Maybelline-Volumizing-Buildable-Lengthening-Multiplying/dp/B08H4FSGDW/ref=sr_1_12?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-12",
    description: 'Sky high lash impact from every angle, full volume meets limitless length',
    category: 2,
  },
  {
    id: 6,
    name: 'Makeup Remover ',
    img:"https://m.media-amazon.com/images/I/81z8tQe35hL._AC_UL480_QL65_.jpg",
    gal1:"https://m.media-amazon.com/images/I/81z8tQe35hL._AC_UL480_QL65_.jpg",
    gal2:"https://images-na.ssl-images-amazon.com/images/I/81ZimLGwwaL._SL1500_.jpg",
    gal3:"https://images-na.ssl-images-amazon.com/images/I/71i0OWKabvL._SL1500_.jpg",
    price: 11.96,
    rating:4.5,
    link:"https://www.amazon.com/Neutrogena-Makeup-Removing-Wipes-Count/dp/B00U2VQZDS/ref=sr_1_4?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-4",
    description: 'Twin pack of 25 count soft, pre-moistened Neutrogena Makeup Remover Cleansing Face Wipes to remove makeup and effectively cleanse skin in 1 easy step',
    category: 2,
  },
  {
    id: 7,
    name: 'essence | Lash Princess False Lash Effect Mascara ',
    img:"https://images-na.ssl-images-amazon.com/images/I/71vNRRHMLvL._SL1500_.jpg",
    gal1:"https://images-na.ssl-images-amazon.com/images/I/71vNRRHMLvL._SL1500_.jpg",
    gal2:"https://images-na.ssl-images-amazon.com/images/I/31cd26kbBLL.jpg",
    gal3:"",
    price: 12.09,
    rating:4.4,
    link:"https://www.amazon.com/essence-Princess-Effect-Mascara-Cruelty/dp/B00T0C9XRK/ref=sr_1_3?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-3",
    description: 'If you receive this mascara UNWRAPPED, it did not come from essence cosmetics.',
    category: 2,
  },

  {
    id: 8,
    name: 'Olaplex Hair Perfector',
    img:"https://m.media-amazon.com/images/I/71gnxxwxAXL._AC_UL480_QL65_.jpg",
    gal1:"https://m.media-amazon.com/images/I/71gnxxwxAXL._AC_UL480_QL65_.jpg",
    gal2:"https://images-na.ssl-images-amazon.com/images/I/71oTGRpW-fL._SL1500_.jpg",
    gal3:"https://images-na.ssl-images-amazon.com/images/I/81F5mznpB8L._SL1500_.jpg",
    price: 28,
    rating:4.7,
    link:"https://www.amazon.com/Olaplex-Hair-Perfector-Repairing-Treatment/dp/B00SNM5US4/ref=sr_1_10?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-10",
    description: 'OLAPLEX No.3 at home hair repairing treatment. ',
    category: 3,
  },
  {
    id: 9,
    name: 'Castor Oil (2oz) USDA Certified Organic',
    img:"https://m.media-amazon.com/images/I/615AiiiHAUL._AC_UL480_QL65_.jpg",
    gal1:"https://m.media-amazon.com/images/I/615AiiiHAUL._AC_UL480_QL65_.jpg",
    gal2:"https://images-na.ssl-images-amazon.com/images/I/71Yo6DxPm0L._SL1500_.jpg",
    gal3:"https://images-na.ssl-images-amazon.com/images/I/71lHRBvuRLL._SL1500_.jpg",
    price: 9.99,
    rating:4.67,
    link:"https://www.amazon.com/Certified-Kate-Stimulate-Eyelashes-Treatment/dp/B01NALN8Q9/ref=sr_1_32?dchild=1&qid=1614153279&s=beauty-intl-ship&sr=1-32",
    description: 'USDA CERTIFIED ORGANIC CASTOR OIL - Kate Blanc’s Organic Cold Pressed Castor Oil is certified by USDA and is guaranteed to be authentic, pure, natural, and hexane free. 100% Authentic or Full Refund.',
    category: 3,
  },

  {
    id: 10,
    name: 'Dove Body Wash',
    img:"https://m.media-amazon.com/images/I/71NbfFpRvzL._AC_UL480_QL65_.jpg",
    gal1:"https://m.media-amazon.com/images/I/71NbfFpRvzL._AC_UL480_QL65_.jpg",
    gal2: "https://images-na.ssl-images-amazon.com/images/I/81JFz0S791L._SL1500_.jpg",
    gal3: "https://images-na.ssl-images-amazon.com/images/I/81c7wVTytuL._SL1500_.jpg",
    price: 12.09,
    rating:4.0,
    link:"https://www.amazon.com/Dove-Body-Wash-Pump-Moisture/dp/B00MEDOY2G/ref=sr_1_15?dchild=1&qid=1614154091&s=beauty-intl-ship&sr=1-15",
    description: 'Dove Deep Moisture Body Wash is Just As Effective for Cleaning Hands!',
    category: 4,
  },
  {
    id: 11,
    name: 'Weleda Skin Food Original Ultra-Rich Body Cream',
    img:"https://m.media-amazon.com/images/I/71keoBqoiYL._AC_UL480_QL65_.jpg",
    gal1:"https://m.media-amazon.com/images/I/71keoBqoiYL._AC_UL480_QL65_.jpg",
    gal2:"https://images-na.ssl-images-amazon.com/images/I/81YAH1vge%2BL._SL1500_.jpg",
    gal3:"https://images-na.ssl-images-amazon.com/images/I/71SHtxvUjbL._SL1500_.jpg",
    price: 17.96,
    rating:4.35,
    link:"https://www.amazon.com/Weleda-Skin-Food-2-5-Ounce/dp/B000ORV3NC/ref=sr_1_37?dchild=1&qid=1614153279&s=beauty-intl-ship&sr=1-37",
    description: 'Skin Food is a universal savior of dry, rough skin on faces, elbows, hands and feet.',
    category: 4,
  }
]


/*
Copyright Google LLC. All Rights Reserved.
Use of this source code is governed by an MIT-style license that
can be found in the LICENSE file at https://angular.io/license
*/
